version: "3.7"

services:

  ### Anwendung ###
 
  BookStoreJ:
    image: ghcr.io/jexxa-projects/bookstorej:latest
    ports:
      - "7504:7504"

    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider 'http://localhost:7504/BoundedContext/isRunning/'"]
      interval: 10s
      timeout: 10s
      retries: 3

    deploy:
      replicas: 2
      update_config:
        order: start-first        # Configure rolling updates
        failure_action: rollback

      rollback_config:
        parallelism: 1            # Rollback config
        order: start-first

      restart_policy:
        condition: on-failure


  ### Infrastruktur ###
  
  SwaggerUI:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - '8080:8080'
      
  ActiveMQ:
    image: rmohr/activemq

  Postgres:
    image: postgres:14.2-alpine
    user: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:


